### ISSUE TITLE
Duplicate colors (red and green)

### ISSUE THREAD

**Issue by pkazmier** [diegoulloao/neofusion.iterm#2]
Love the theme, but I need to tweak it because using the same color for both red and green slots breaks too many things for me. I was hoping you might have an alternate suggestion.

**Comment by diegoulloao** [comment]
Is git diff what's not working properly for you? Or something else?

**Comment by pkazmier** [comment]
Too many tools I use (task warrior, eza, powerlevel10k) expect a distinction between ascii red and green, so for now I've set ascii color 2 to the same green as its bright variant (the olive-like one). Not sure I really like it though. I may try to find some other variant of blue for that slot. As I know this is a matter of taste, we can close this issue. Thanks.

**Comment by diegoulloao** [comment]
You can try replacing the blue color by `#5db2f8`
Otherwise, you can pick any of these colors: https://github.com/diegoulloao/neofusion.nvim/blob/main/lua/neofusion/palette.lua

<img width="370" alt="Screenshot 5" src="https://github.com/diegoulloao/neofusion.iterm/assets/45423661/36482b52-6023-4da9-956e-a8a0c753c85c">

Hope it can help
